---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

Through my work in this course, I have significantly enhanced my skills and abilities in data science, particularly in R. I have developed a solid understanding of essential skills such as manipulating datasets with dplyr pipelines and creating well-labeled, organized graphs with ggplot. These are skills I have already applied in other classes, and I see myself continuing to use them throughout my career.

In learning and applying these skills, I also found myself extending my thinking (critical thinking) through the creation of diagrams and exploring better approaches to solving problems. With this in mind, I believe I have most improved in my ability to critically think my way to a solution using the tools I have learned.

One artifact from my portfolio that demonstrates this growth is the code I used for PE-4-2 (and a few other targets). In this code, I utilized a dplyr pipeline to select specific columns necessary for the problem. I then pivoted the columns longer and recoded the factors using a mutate function. After preparing the data frame, I piped it into ggplot, where I reordered the factors, created facets, added labels, and resized the x-axis text to improve readability.

This problem was challenging as I had to integrate newly learned forcats functions in order to manipulate factors while applying my understanding of dplyr pipelines and ggplot.

In addition to data manipulation and visualization, function creation was another area in which I experienced significant growth as a data scientist. Throughout the quarter, we frequently discussed the importance of efficiency, particularly when dealing with repetitive tasks. Functions, as it turns out, are one of the best ways to handle repetitive tasks without rewriting code multiple times.

An artifact from my portfolio that highlights the importance of functions is PE-3-Across. The arguments of this function included a data frame and one or more column names from that data frame, provided as a vector. For each column specified, the function re-scaled the values in the column (using a re-scale function we had previously created) to a range of 0 to 1, allowing for a clearer understanding of the data. Thanks to this function and the re-scale function, I was able to efficiently re-scale multiple columns in a data frame in a single step.
